Fix build error due to mismatched types
Error was:

| literals.cpp: In function 'libp2p::common::Hash256 libp2p::common::operator""_hash256(const char*, size_t)':
| literals.cpp:19:36: error: no matching function for call to 'min(size_t&, long unsigned int)'
|    19 |     std::copy_n(c, std::min(s, 32ul), hash.rbegin());
|       |                                    ^