Fix build errors due to missing include
Errors were:

| connectivity.cpp:151:42:   required from here
| sublogger.hpp:42:9: error: no matching function for call to '=::log(spdlog::level::level_enum&, std::string&, const std::__cxx11::basic_string<char>&)'
|    42 |         log_->log(lvl, prefix_, args...);
|       |         ^~~~

| topic_subscriptions.cpp:54:37:   required from here
| sublogger.hpp:42:9: error: no matching function for call to 'spdlog::logger::log(spdlog::level::level_enum&, std::string&, const std::__cxx11::basic_string<char>&, const long long unsigned int&, const long long unsigned int&)'
|    42 |         log_->log(lvl, prefix_, args...);
|       |         ^~~~

| remote_subscriptions.cpp:28:56:   required from here
| sublogger.hpp:42:9: error: no matching function for call to 'spdlog::logger::log(spdlog::level::level_enum&, std::string&, const std::__cxx11::basic_string<char>&)'
|    42 |         log_->log(lvl, prefix_, args...);
|       |         ^~~~

| kad_server.cpp:40:42:   required from here
| sublogger.hpp:42:9: error: no matching function for call to 'spdlog::logger::log(spdlog::level::level_enum&, std::string&, const std::__cxx11::basic_string<char>&)'
|    42 |         log_->log(lvl, prefix_, args...);
|       |         ^~~~