Fix build error due to missing include
Error was:

| literals.cpp: In function 'libp2p::common::Hash256 libp2p::common::operator""_hash256(const char*, size_t)':
| literals.cpp:17:36: error: no matching function for call to 'min(size_t&, long unsigned int)'
|    17 |     std::copy_n(c, std::min(s, 32ul), hash.rbegin());
|       |                                    ^